# Generated by Django 5.2.13 on 2026-06-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('file', models.FileField(upload_to='files/')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
