# Generated by Django 5.2.13 on 2026-05-21 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('genre', models.CharField(choices=[('pvp', 'PvP'), ('pve', 'PvE'), ('rpg', 'RPG'), ('fps', 'FPS'), ('mmo', 'MMO'), ('adventure', 'Adventure'), ('strategy', 'Strategy'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('racing', 'Racing'), ('multiplayer', 'Multiplayer')], default='pvp', max_length=50, verbose_name='Genre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
